import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  Box,
  Column,
  Contain,
  Flex,
  Heading,
  Row,
  Text,
} from "@components/system";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex flexDirection="column" height="100%">
          <Box my="auto">
            <Contain>
              <Row>
                <Column col={[12, 10, 8]} inset={[null, 1, 2]}>
                  <Flex
                    alignItems="center"
                    justifyContent="center"
                    flexDirection="column"
                  >
                    <Heading as="h1" mb="s">
                      You are Lost!
                    </Heading>
                    <Text textAlign="center" mb="m">
                      404
                    </Text>
                    <Link href="/">Go Home</Link>
                  </Flex>
                </Column>
              </Row>
            </Contain>
          </Box>
        </Flex>{" "}
      </main>
    </div>
  );
};

export default Home;
