import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import {
  Box,
  Card,
  Column,
  Contain,
  Flex,
  Heading,
  Row,
  Text,
} from "@components/system";
import { Button } from "@components/atoms";
import { BaseLayout } from "@components/BaseLayout";

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex flexDirection="column" height="100%" bg="bg">
        <Box my="auto">
          <Contain>
            <Row>
              <Column col={[12, 10, 8]} inset={[null, 1, 2]}>
                <Flex
                  alignItems="center"
                  justifyContent="center"
                  flexDirection="column"
                >
                  <Heading as="h1" mb="s">
                    You are Lost!
                  </Heading>
                  <Text textAlign="center" mb="m">
                    404
                  </Text>
                  <Link href="/">Go Home</Link>
                  <Button variant="secondary" size="medium">
                    Press Here!
                  </Button>
                  <Card backgroundColor="white" mx="m">
                    <Text color="primary">HEHEHEHEH</Text>
                  </Card>
                </Flex>
              </Column>
            </Row>
          </Contain>
        </Box>
      </Flex>
    </BaseLayout>
  );
};

export default Home;
